[platformio]
default_envs = IO_16_8_1

[env:IO_16_8_1]
platform = https://github.com/maxgerhardt/platform-raspberrypi
framework = arduino
board = pico
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
monitor_speed = 115200
build_flags =
    -D PICO_STDIO_USB ; enable stdio over USB
lib_deps =
    mkalkbrenner/WavePWM
    https://github.com/PPUC/Adafruit_NeoPixel#b1dc07a3dd6d019afd0a15bb59f20abc41e6225a
    https://github.com/PPUC/WS2812FX#1ab50cabb02fc0705c86c21ee9fbde7922835ffa
    Bounce2
    RPI_PICO_TimerInterrupt
