#pragma once

#define PPUC_FIRMWARE_VERSION_MAJOR 0
#define PPUC_FIRMWARE_VERSION_MINOR 3
#define PPUC_FIRMWARE_VERSION_PATCH 0

#define _PPUC_FIRMWARE_STR(x) #x
#define PPUC_FIRMWARE_STR(x) _PPUC_FIRMWARE_STR(x)

#define PPUC_FIRMWARE_VERSION                                      \
  PPUC_FIRMWARE_STR(PPUC_FIRMWARE_VERSION_MAJOR) "."              \
      PPUC_FIRMWARE_STR(PPUC_FIRMWARE_VERSION_MINOR) "."          \
          PPUC_FIRMWARE_STR(PPUC_FIRMWARE_VERSION_PATCH)
